mod mailcoach_newsletter_repository;
mod markdown_static_repository;

pub use mailcoach_newsletter_repository::MailcoachNewsletterRepository;
pub use markdown_static_repository::MarkdownStaticRepository;
